spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
#  data:
#    cassandra:
#      keyspace-name: tacocloud
#      schema-action: recreate-drop-unused
#      local-datacenter: datacenter1